# etap build
FROM node:20 AS build

WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .

ARG VITE_API_BASE
ENV VITE_API_BASE=$VITE_API_BASE

RUN npm run build

# etap serwowania
FROM nginx:1.25

# nadpisanie domyślnego try_files, żeby SPA działało
RUN sed -i 's|try_files \$uri \$uri/ =404;|try_files \$uri /index.html;|' /etc/nginx/conf.d/default.conf

COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
