version: "3.9"
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: auth_demo
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 3s
      retries: 10

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    env_file:
      - ./server/.env
    ports:
      - "4000:4000"
    volumes:
      - ./server/src:/app/src
    depends_on:
      db:
        condition: service_healthy
    environment:
      - MYSQL_HOST=db
    command: sh -c "npx prisma generate && npm run dev"

  # client:
  #   build: ./client
  #   environment:
  #   - VITE_API_BASE=http://localhost:4000
  #   ports:
  #   - "5173:5173"
  #   volumes:
  #   - ./client/src:/app/src   # tylko src
  #   depends_on:
  #   - server
  #   command: npm run dev

volumes:
  db_data:
