version: "3.9"

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: auth_demo
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 3s
      retries: 10

  server:
    build: ./server
    env_file:
      - ./server/.env
    depends_on:
      db:
        condition: service_healthy
    environment:
      - MYSQL_HOST=db
      - VIRTUAL_HOST=app.gokart-training.cloud
      - VIRTUAL_PORT=4000
      - LETSENCRYPT_HOST=app.gokart-training.cloud
      - LETSENCRYPT_EMAIL=piotrek789150@gmail.com
    command: sh -c "npx prisma migrate deploy && npm start"
    networks:
      - backend
      - proxy

  client:
    build:
      context: ./client
      args:
        VITE_API_BASE: "https://app.gokart-training.cloud"
    # Montujemy gotowy build z Vite
    volumes:
      - ./client/dist:/usr/share/nginx/html:ro
    environment:
      - VIRTUAL_HOST=app.gokart-training.cloud
      - LETSENCRYPT_HOST=app.gokart-training.cloud
      - LETSENCRYPT_EMAIL=piotrek789150@gmail.com
    networks:
      - proxy

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs:ro
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    networks:
      - proxy

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    depends_on:
      - nginx-proxy
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    networks:
      - proxy

volumes:
  db_data:
  certs:
  vhost:
  html:

networks:
  backend:
  proxy:
